# Generated by Django 3.2.5 on 2021-11-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accounts_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
