# Generated by Django 3.2.5 on 2021-11-24 12:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(default='None', max_length=30)),
                ('short_descipt', models.CharField(max_length=200)),
                ('expected_number', models.IntegerField(default=5)),
                ('passed', models.BooleanField(default=False)),
                ('post', models.TextField(default=None)),
                ('hold_time', models.DateField(default=datetime.date.today)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit_time', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, default=None, max_length=200)),
                ('comment_user', models.CharField(blank=True, default=None, max_length=30)),
                ('pic', models.ImageField(blank=True, default='/media/smile.png', null=True, upload_to='')),
                ('registered_members', models.ManyToManyField(to='account.Accounts')),
            ],
        ),
    ]
