# Generated by Django 3.2.5 on 2021-12-11 02:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_descipt', models.CharField(max_length=200)),
                ('expected_number', models.IntegerField(default=5)),
                ('post', models.TextField(default=None)),
                ('hold_time', models.DateField(default=datetime.date.today)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit_time', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('passed', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('pic', models.ImageField(blank=True, default='/media/smile.png', null=True, upload_to='')),
                ('comment_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='account.accounts')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.department')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uname', to='account.accounts')),
                ('registered_members', models.ManyToManyField(to='account.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentstr', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accounts')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
        ),
    ]
