# Generated by Django 3.2.5 on 2021-11-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
