# Generated by Django 3.2.5 on 2021-11-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment_user',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
